### PR TITLE
issue #324 - fix how composer settings are created in the `GeneratorOptions` class

### LINKED ISSUE #324: Composer Settings Are Incorrectly Created With A Numeric Index In The Composer JSON File
**Describe the bug**

When using the `--composer-settings` option in the PackageGenerator, the JSON keys are not correctly written to the composer.json file. They are written with a numeric key (as a string) when it should be the first key from the command line option.

Example:

```
--composer-settings="autoload.psr-4.Custom\SoapClient\:./Custom/SoapClient/"
```
In this example, the first key should be "autoload." However, the key is written to composer.json as a "0" or "1", depending on the number of times the `--composer-settings` option is used.

**To Reproduce**

Here is an example Windows batch file that our group uses to generate the package:

```cmd
php ./wsdltophp.phar generate:package ^
  --urlorpath="https://url/to/wsdl" ^
  --destination="C:\path\to\package" ^
  --composer-name="author-name/package-name" ^
  --namespace="Test\Namespace" ^
  --composer-settings="config.disable-tls:true" ^
  --composer-settings="autoload.psr-4.Custom\SoapClient\:./Custom/SoapClient/" ^
  --validation=false ^
  --soapclient="Custom\SoapClient" ^
  --force
```

And here is the final output in composer.json:

```json
{
    "name": "author-name/package-name",
    "description": "Package generated from https://url/to/wsdl using wsdltophp/packagegenerator",
    "require": {
        "php": ">=7.4",
        "ext-dom": "*",
        "ext-mbstring": "*",
        "ext-soap": "*",
        "wsdltophp/packagebase": "~5.0"
    },
    "autoload": {
        "psr-4": {
            "Test\\Namespace\\": "./src\\Test\\Namespace"
        }
    },
    "0": "config.disable-tls:true",
    "1": "autoload.psr-4.Custom\\SoapClient\\:./Custom/SoapClient/"
}
```
**Expected behavior**

The JSON is not formatted correctly. 

Instead of this:

```json
"0": "config.disable-tls:true",
"1": "autoload.psr-4.Custom\\SoapClient\\:./Custom/SoapClient/"
```

It should be this:

```json

    "autoload": {
        "psr-4": {
            "Custom\\SoapClient\\": "./Custom/SoapClient/"
        }
    },
    "config": {
      "disable-tls": true
    }

```
**Additional context**

Looking at the source code, the `GeneratorOptions` class has a static method called [`dotNotationToArray`](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/ConfigurationReader/GeneratorOptions.php#L264). It appears this method is responsible for exploding the string via the `.` char, which is how the composer arguments are delimited on the command line.

I did some testing locally using the PHP interpreter. Unfortunately I am not able to fork the repo and install the dependencies due to limitations at my organization. However, when using the PHP interpreter, I called `dotNotationToArray` and the results are as expected (see below).

But one thing that caught my attention is that the `dotNotationToArray` method is marked as static in the source code. Yet it accesses the `$array` value by reference. That is one difference between the source code and the command line sample shown below. I don't know if this is an issue, but it caught my attention to see a static function access a value by reference when the containing class is not static, which is the case for `GeneratorOptions`. In other words, the `GeneratorOptions` class is instance, the `$array` is instance, but the `dotNotationToArray` function is static.

```cmd
php > $value = "config.disable-tls:true";
php > $path = implode('', array_slice(explode(':', $value), 0, 1));
php > $val = implode(':', array_slice(explode(':', $value), 1));
php > $settings = [];
php > function dotNotationToArray(string $string, $value, array &$array): void
php > {
php {     $keys = explode('.', $string);
php {     foreach ($keys as $key) {
php {         $array = &$array[$key];
php {     }
php {     $array = ('true' === $value || 'false' === $value) ? 'true' === $value : $value;
php { }
php >
php > dotNotationToArray($path, $val, $settings);
php > var_dump($settings);
php shell code:1:
array(1) {
  'config' =>
  array(1) {
    'disable-tls' =>
    bool(true)
  }
}
php >
```
** Extra Information **

This is likely unrelated to the `--composer-settings` issue, but it's worth noting that the package source folder is not correctly written to composer.json, similar to issue #306. The value should have forward slashes but instead it has back slashes.

Instead of this:

```json
    "autoload": {
        "psr-4": {
            "Test\\Namespace\\": "./src\\Test\\Namespace"
        }
    },
```

It should be this:

```json
    "autoload": {
        "psr-4": {
            "Test\\Namespace\\": "./src/Test/Namespace/"
        }
    },
```

### PR DESCRIPTION
**Pull request by ajoh504**
The `GeneratorOptions::setOptionValue` method contains a new condtion to check if the current input contains composer settings, and internally calls `setComposerSettings` if so. The unit tests attempt to test the following possibilites:
1. Composer settings are sent via command line
2. Composer settings are sent via a PHP project script

This fixes issue #324 where, when adding composer settings via the command line, the composer.json file was written as this:

```
"0": "config.disable-tls:true",
"1": "autoload.psr-4.Custom\\SoapClient\\:./Custom/SoapClient/"
```

instead of this:

```
"autoload": {
    "psr-4": {
        "Custom\\SoapClient\\": "./Custom/SoapClient/"
    }
},
"config": {
  "disable-tls": true
}
```

### CODE REVIEW

File: tests/File/ComposerTest.php [hunk 1]
```diff
@@ -66,6 +66,31 @@ public function testBingWithSettings(): void
...
+                'require-dev.rector/rector:^2'
+            ])
+        ;
+        $composerFile = new Composer($instance, 'composer');
+        $composerFile
+            ->setRunComposerUpdate(false)
+            ->write()
+        ;
+
+        $this->assertJson(json_encode($composerFile->getFileName()));
```
Comment (mikaelcom) [inline tests/File/ComposerTest.php]: I was expecting something more like `$this->assertSameFileContent('ValidBingComposerJsonSettings', $composerFile, 'json');`

File: src/ConfigurationReader/GeneratorOptions.php
Comment (mikaelcom) [inline src/ConfigurationReader/GeneratorOptions.php]:
```suggestion
    public function setOptionValue(string $optionName, $optionValue, array $values = [], bool $callCustomMethod = true): self
```

**Review by mikaelcom — COMMENTED** [review]
To be adapted 😉

File: tests/resources/generated/ValidBingComposerSettingsAdditionalOptions.json [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+        "ext-mbstring": "*",
+        "ext-soap": "*",
+        "wsdltophp/packagebase": "~5.0",
+        "wsdltophp/wssecurity": "dev-master"
+    },
+    "autoload": {
+        "psr-4": {
+            "": "./src/"
+        }
+    },
```
Comment (mikaelcom) [inline tests/resources/generated/ValidBingComposerSettingsAdditionalOptions.json]:
```suggestion
    },
```

the issue is the whitespaces 😉

**Review by mikaelcom — APPROVED** [review]

**Review by mikaelcom — APPROVED** [review]
let me know if you can't merge by yourself

**Comment by ajoh504** [comment]
It looks like I only have the option to "Close with comment."
